# Generated by Django 4.2 on 2023-06-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostapp', '0005_rename_dep_description_departments_dep_decription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_phone', models.CharField(max_length=255)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_department', models.CharField(max_length=255)),
            ],
        ),
    ]
